# Generated by Django 4.1.4 on 2023-01-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age_yr",
            field=models.IntegerField(default=26),
        ),
        migrations.AddField(
            model_name="user",
            name="height_cm",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="user",
            name="weight_kg",
            field=models.DecimalField(decimal_places=2, default=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="user",
            name="sex",
            field=models.CharField(
                choices=[("MALE", "M"), ("FEMALE", "F")], default="M", max_length=10
            ),
        ),
    ]
