# Generated by Django 4.1.4 on 2023-01-14 20:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meal",
            fields=[
                ("protein_grams", models.DecimalField(decimal_places=2, max_digits=6)),
                ("carb_grams", models.DecimalField(decimal_places=2, max_digits=6)),
                ("sat_fat_grams", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "unsat_fat_grams",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("total_kcal", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
    ]
