# Generated by Django 5.0.4 on 2024-04-14 21:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('protein_grams', models.DecimalField(decimal_places=2, max_digits=6)),
                ('carb_grams', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sat_fat_grams', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unsat_fat_grams', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_kcal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
