# Generated by Django 5.0.4 on 2024-04-14 21:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedDiet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('suggested_protein', models.DecimalField(decimal_places=1, max_digits=8)),
                ('suggested_carb', models.DecimalField(decimal_places=1, max_digits=8)),
                ('suggested_sat_fat', models.DecimalField(decimal_places=1, max_digits=8)),
                ('suggested_unsat_fat', models.DecimalField(decimal_places=1, max_digits=8)),
                ('suggested_water', models.DecimalField(decimal_places=1, max_digits=8)),
                ('basal_metabolism', models.DecimalField(decimal_places=1, max_digits=8)),
            ],
        ),
    ]
