# Generated by Django 4.1.4 on 2023-01-14 20:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SuggestedDiet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "suggested_protein",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("suggested_carb", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "suggested_sat_fat",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "suggested_unsat_fat",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "basal_metabolic",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
            ],
        ),
    ]
