# Generated by Django 5.0.4 on 2024-04-14 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggested_diets', '0002_suggesteddiet_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggesteddiet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_diet', to=settings.AUTH_USER_MODEL),
        ),
    ]
