# Generated by Django 4.1.4 on 2023-01-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suggested_diets", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggesteddiet",
            name="suggested_water",
            field=models.DecimalField(decimal_places=2, default=2, max_digits=8),
        ),
    ]
