# Generated by Django 4.1.4 on 2023-01-15 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suggested_diets", "0004_alter_suggesteddiet_suggested_water"),
    ]

    operations = [
        migrations.RenameField(
            model_name="suggesteddiet",
            old_name="basal_metabolic",
            new_name="basal_metabolism",
        ),
    ]
