# Generated by Django 4.1.4 on 2023-01-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "suggested_diets",
            "0005_rename_basal_metabolic_suggesteddiet_basal_metabolism",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="suggesteddiet",
            name="basal_metabolism",
            field=models.DecimalField(decimal_places=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name="suggesteddiet",
            name="suggested_carb",
            field=models.DecimalField(decimal_places=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name="suggesteddiet",
            name="suggested_protein",
            field=models.DecimalField(decimal_places=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name="suggesteddiet",
            name="suggested_sat_fat",
            field=models.DecimalField(decimal_places=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name="suggesteddiet",
            name="suggested_unsat_fat",
            field=models.DecimalField(decimal_places=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name="suggesteddiet",
            name="suggested_water",
            field=models.DecimalField(decimal_places=1, max_digits=8),
        ),
    ]
