# Generated by Django 5.0.4 on 2024-04-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('total_protein_g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_carb_g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_sat_fat_g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_unsat_fat_g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_kcal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity_g', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
